### ISSUE TITLE
How to use the Opacity Modifier?

### ISSUE THREAD

**Issue by optikalefx** [L-Blondy/tw-colors#51]
In the docs here https://tailwindcss.com/docs/customizing-colors#using-css-variables

it says

>>>
If you’d like to define your colors as CSS variables, you’ll need to define those variables as just the color channels if you want them to work with the [opacity modifier syntax](https://tailwindcss.com/docs/text-color#changing-the-opacity):
>>>

and to define CSS variables this way

```css
@layer base {
  :root {
    --color-primary: 255 115 179;
    --color-secondary: 111 114 185;
    /* ... */
  }
}
```

Since this plugin doesn't want us to use variables, how can we make use of the opacity modifier? We can't pass 

```
createThemes({
      light: {
        'lighter-gray': '248 248 248',
      },
```

As such, do we lose the functionality of the opacity modifier if we use tw-colors?
