### ISSUE TITLE
Tailwind v4

### ISSUE THREAD

**Issue by Sparticuz** [L-Blondy/tw-colors#52]
Is there any information on upgrading to Tailwind v4?

**Comment by L-Blondy** [comment]
I added Tailwind v4 support in version `4.0.0-beta.0`, however due to the limited support for the js config file in tailwind 4 there are a few breaking changes:

- **data attributes** are no longer supported to set the theme
- **default themes** are no longer supported
- **default color opacity** is no longer supported in the config
- **slash** in className is no longer supported

To install it run `npm i -D tw-colors@4.0.0-beta.0`

**Note:** v3.3.2 remains available for Tailwind v3 users

Let me know if you have any issue.

**Comment by codeblech** [comment]
readme say:
> With Tailwind v4's release, you may want to consider using Tailwind's built-in CSS configuration for managing multiple themes instead.

can someone please point to that part of tailwind docs?

**Comment by hilja** [comment]
I've done color themes like this in Tailwind 4:

```css
/* tailwind.css */
@custom-variant dark (&:is(.dark, .dark *));

:root {
  --twc-base-1: var(--color-stone-50);
  --twc-base-2: var(--color-stone-100);
  --twc-base-3: var(--color-stone-200);
}

.dark {
  --twc-base-1: var(--color-stone-950);
  --twc-base-2: var(--color-stone-900);
  --twc-base-3: var(--color-stone-800);
}

@theme {
  --color-base-1: var(--twc-base-1);
  --color-base-2: var(--twc-base-2);
  --color-base-3: var(--twc-base-3);
}
```

I feel like this plugin is obsolete now, it has served me well though, thanks for maintaining it :)

This has the added benefit that you can use your custom theme colors in `--value()` when defining utilities:

```css
@utility percent-gradient-* {
  background-image: linear-gradient(
    to right,
    --value(--color-*) var(--percent-val),
    var(--color-base-8) var(--percent-val)
  );
}
```

**Comment by felipemullen** [comment]
> readme say:
> 
> > With Tailwind v4's release, you may want to consider using Tailwind's built-in CSS configuration for managing multiple themes instead.
> 
> can someone please point to that part of tailwind docs?

The official [theme page in the docs](https://tailwindcss.com/docs/theme) doesn't give an example, but it is easy to implement in css, like so:

```css
@theme {
    --color-primary: #268bd2;
    --color-secondary: #b58900;
    --color-background: #002b36;
    --color-foreground: #eee8d5;
    --color-muted: #586e75;
}

@layer base {
    [data-theme='monokai'] {
        --color-primary: #2e8be2;
        --color-secondary: #fd971f;
        --color-background: #272822;
        --color-foreground: #f8f8f2;
        --color-muted: #75715e;
    }

    [data-theme='dracula'] {
        --color-primary: #bd93f9;
        --color-secondary: #ff79c6;
        --color-background: #282a36;
        --color-foreground: #f8f8f2;
        --color-muted: #6272a4;
    }
}
```

and then use the colors in the html

```
<body data-theme="sand">
    <div class="bg-primary text-secondary">themed text content</div>
</body>
```
